spring:
  profiles:
    active: dev
  application:
    name: redis-learn
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis_learn?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: javacppgorust
  # session ????????
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis ??
  redis:
    host: 192.168.81.129
    port: 6379
    password: javacppgorust

mybatis:
  mapper-locations: 'classpath*:/**/mapper/**Mapper.xml'
  type-aliases-package: com.wly.redis.model
server:
  port: 8080

