spring:
  profiles:
    active: dev
  application:
    name: redis-learn
  # DataSource Config
  # session ????????
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis ??
  redis:
    host: localhost
    port: 6379

